//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLPAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILLPAY()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public string BillPay_id { get; set; }
        public System.DateTime Date { get; set; }
        public string PayType_id { get; set; }
        public string Customer_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PAYTYPE PAYTYPE { get; set; }
    }
}
