//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENT()
        {
            this.BILLs = new HashSet<BILL>();
        }

        [DisplayName("Mã giá phòng")]
        public string Rent_id { get; set; }

        [DisplayName("Giá phòng")]
        public int Price { get; set; }

        [DisplayName("Tình trạng")]
        public Nullable<bool> IsActive { get; set; }

        [DisplayName("Từ ngày")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime From_Date { get; set; }

        [DisplayName("Đến ngày")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> To_Date { get; set; }

        [DisplayName("Mã loại phòng")]
        public string RoomType_id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual ROOMTYPE ROOMTYPE { get; set; }
    }
}
