//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENT()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public string Rent_id { get; set; }
        public int Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string RoomType_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual ROOMTYPE ROOMTYPE { get; set; }
    }
}
